# Generated by Django 3.1.2 on 2020-10-06 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentmodel',
            fields=[
                ('stid', models.IntegerField(primary_key=True, serialize=False)),
                ('stname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marksmodel',
            fields=[
                ('marksid', models.IntegerField(primary_key=True, serialize=False)),
                ('maths', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('computers', models.IntegerField()),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='app.studentmodel')),
            ],
        ),
    ]
